config/routes.rb
Rails.application.routes.draw do
  
  
  root "events#index"
  resources :events do

    resources :registrations
end
resource :session, only: [:new, :create, :destroy]
resources :users
get "signup" => "users#new"
  # For details on the DSL availab
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy
validates :name,:location, presence: true 
validates :description, length: {minimum: 25} 
validates :price, numericality: {greater_than_or_equal_to: 0} 
validates :capacity,numericality: {only_integer: true,greater_than: 0} 
validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }
def self.upcoming
   where("starts_at > ?",Time.now).order("starts_at")
   
   
    end
 
 
    def free?
        price.blank? || price.zero?
    end

 def sold_out?
      (capacity - registrations.size).zero?
    end

  end 

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user
  
  HOW_HEARD_OPTIONS=[
    'News letter',
    'Blog post',
    'Twitter',
    'web search',
    'other'
  ]
  validates :how_heard,inclusion: {in: HOW_HEARD_OPTIONS}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
   has_secure_password
  validates :name, presence: true 
  validates :email, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private

    def require_signin
      unless current_user
        session[:intended_url] = request.url
        redirect_to new_session_url, alert: "Please sign in first!"
      end
    end
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?
  def require_admin
  unless current_user_admin?
    redirect_to root_url, alert: "Unauthorized access!"
  end
end

def current_user_admin?
  current_user && current_user.admin?
end
helper_method :current_user_admin?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_signin, except: [:index, :show]
    before_action :require_admin, except: [:index, :show]
def index
    @events=Event.upcoming
end
def show 
    @event=Event.find(params[:id])
end
def new
    @event=Event.new 
end
def edit
    @event=Event.find(params[:id])
end
def update
    @event=Event.find(params[:id])
    if @event.update( event_params)
    redirect_to @event,notice: "Event successfully updated"
    else 
    render :edit
    end
end
def destroy
    @event=Event.find(params[:id])
    @event.destroy
    redirect_to events_url
 end
 def create
      @event=Event.new ( event_params)
     if @event.save
        redirect_to @event,notice: "Event successfully created"
     else 
        render :new
     end
 end
private
def event_params
    event_params=params.require(:event).permit(:name,:description,:location,:price,:starts_at, :capacity, :image_file_name)
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    before_action :require_signin
   before_action :set_event
    def index
       
       @registrations=@event.registrations 
    end
    def new
        
        @registration=@event.registrations.new 
    end
    def create
       
        @registration=@event.registrations.new (registration_params)
        @registration.user = current_user
       if  @registration.save
          redirect_to event_registrations_url(@event),notice: "registration successfully created"
       else 
          render :new
       end
   end
   private
   def registration_params
    params.require(:registration).permit(:how_heard)
end
def set_event
    @event=Event.find(params[:event_id])
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to (session[:intended_url] || user),
                   notice: "Welcome back, #{user.name}!"
      session[:intended_url] = nil
        else
          flash.now[:alert] = "Invalid email/password combination!"
          render :new
        end  
    end
    def destroy
        session[:user_id] = nil
        redirect_to events_url, notice: "You're now signed out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
       @users=User.all 
    end

     def show
        @user=User.find(params[:id])
        @registrations=@user.registrations 
     end
     def edit
        @user = User.find(params[:id])
      end
     def new
        @user = User.new
     end
     def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id

          redirect_to @user, notice: "Thanks for signing up!"
        else
          render :new
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil
        redirect_to events_url, alert: "Account successfully deleted!"
      end 
    def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
    end
    private
      
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def require_correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

def price(event)
 if event.free?
    "Free"
else
  number_to_currency(event.price, precision: 0) 
end
    end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
    def register_or_sold_out(event)
        if event.sold_out?
            content_tag(:span,"sold out!", class: "sold-out")
        else
            link_to "Register",new_event_registration_path(event),class:"register"
end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true ) do |form| %>
 <%= render "shared/errors", object: event %>
  
    <%= form.label :name %>
    <%= form.text_field :name ,autofocus: true%>
  

  
                <%= form.label :description%>
                 <%= form.text_area :description ,rows: 5%>
                <%= form.label :location %>
                 <%= form.text_field :location%>
                <%= form.label :price %>
                 <%= form.number_field :price %>
                <%= form.label :starts_at %>
                 <%= form.datetime_select :starts_at,{ampm: true},{class: "datetime"} %>
                 <%=form.label :capacity %>
                <%= form.number_field :capacity %>

                <%=form.label :image_file_name %>
                <%= form.text_field :image_file_name %>
    
    <%= form.submit %>
  
<% end %>

app/views/events/edit.html.erb
<%= render "form" ,event: @event%>

app/views/events/index.html.erb
 <% @events.each do|event| %>
 <div class="image">
    <%= image_tag event.image_file_name %>
  </div>
    <section class="event">
      <div class="summary">
       <h1><%= link_to event.name ,event%> </h1>
       <h3><%= event.starts_at.strftime("%B %d at %I:%M %P")%> in <%= event.location %> </h3>
       <span class="price">
       <%= price(event) %>
       </span>
               <p>
                   <%= truncate(event.description, length: 10,separator: ' ') %> 
               </p>
      </div>
   </section>
   <% end %>
  <% if current_user_admin? %>
   <section class="admin">
<%= link_to "Add event", new_event_path,class:"button"   %> 
</section>
      <% end %>

 

app/views/events/new.html.erb
<h1>Create new event</h1>
<%= render "form" ,event: @event%>

app/views/events/show.html.erb
<section class="event-details">

 <div class="image">
    <%= image_tag @event.image_file_name %>
  </div>
     <div class="details">
       <h1><%= @event.name %> </h1>
        <h2>
       <%= pluralize(@event.capacity,"spot") %> &bull; <%= price(@event) %>
       </h2>
       <h3><%= @event.starts_at.strftime("%B %d at %I:%M %P")%> in <%= @event.location %> </h3>
       
       <p>
             <%= @event.description %> 
      </p>
        <div class="register">
        <p>
        <%=register_or_sold_out(@event)%>
        </p>
        <p>
<%=link_to "who's registered",event_registrations_path(@event) %>
</p>
        </div>
     </div>
      </section>
<section class= "admin">
<%=link_to "edit",edit_event_path(@event),class:"button" %>
<%=link_to "Delete",@event,class:"button",method: :delete, data: {confirm: "Really?!"} %>
</section>
   

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
  made in <a href="http://pragmaticstudio.com"> the pragmatic studio  </a>
  </p>
  </footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
     <%= link_to image_tag("logo"), root_path %>
   <ul class="left">
      <li>
      <%= link_to "All events", events_path %>
      </li>
   </ul>
  <ul class="right">
       <% if current_user %>
         <li>     
       <%= link_to current_user.name, current_user %>
         </li>
         <li>
    <%= link_to "Sign Out", session_path, method: :delete,
                            class: "button" %>
  </li>
        <% else %>
  <li>
      <%=link_to "Sign In",new_session_path,class: "button"%>
  </li>
  <li> 
      <%= link_to "Sign Up", signup_path, class: "button" %>
  </li>
  <% end %> 
</ul>
</nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" ,event: @event%>
  <div class="content">
   <%= render "layouts/flash" %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" ,event: @event%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

 <% if user.new_record? %>
  <%= f.submit "Create Account" %>
<% else %>
  <%= f.submit "Update Account" %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
   <% if current_user_admin? %>
  <div class="actions">
   <% if current_user?(@user) %>
  <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
   <% end %>
   <% if current_user_admin? %>
  <%= link_to 'Delete Account', @user, method: :delete,
              data: { confirm: "Permanently delete your account!?" },
              class: "button delete" %> 
              <% end %>
</div>
<% end %>
<% if @registration.present? %>
    <h3>Registrations</h3>
    <% @registrations.each do |r| %>
      <div class="registration">
        
         <span class="image">
            <%= link_to image(r.event.image_file_name), r.event %>
          </span>
          <span class="name">
            <%= link_to r.event.name, r.event %>
          </span>

          <span class="date">
            <%= time_ago_in_words(r.created_at) %> ago
          </span>
         
        </div>
      
    <% end %>
  <% end %>
</section>